version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5434:5432/tcp"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: socialnetwork
    volumes:
      - database_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
volumes:
  database_data:
